# Add github config change label to any change of files in docs folder, or subfolders
policy-config-change:
  - templates/policies/**/*

# Add documentation label to any change of files in docs folder, or subfolders
procedure-change:
  - templates/procedures/**/*

# Add code change label to any change of files ending with tf
standards-change:
  templates/standards/**/*