name: Publish
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    types: closed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Install dependency on policy builder
        run: npm install -g @jupiterone/jupiter-policy-builder
      - name: Run Document Generator
        run:  psp build -c ./templates/config.json -t ./templates --noninteractive
      - name: Publish Output to Confluence
        run:  psp publish --confluence --site tottoro --space TS -u ${{ secrets.CONFLUENCE_USERNAME }} -k ${{ secrets.CONFLUENCE_PASSWORD }}
